title: Abhishek Mishra
#logo: /assets/img/your_photo.png   # Place your image here (optional)
#description: >-
  Data Analyst | Python • SQL • Tableau • Power BI  
  Passionate about solving business problems using data.

#show_downloads: true
theme: jekyll-theme-minimal

